### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by tap**
Hi @nwolek -- I have not tested for object breakage, but all objects build on both platforms now.  Cheers!

### CODE REVIEW

**Comment by nwolek** [comment]
@tap - just pushed a fix for the variable outlet issue (commit 889104c). Can you pull it on your end to confirm it compiles on Windows?

**Comment by tap** [comment]
@nwolek they compile fine and the builds are pushed

**Comment by tap** [comment]
and all of the test patchers work fine (except for my inability to use the preset object which might be just me?)

**Comment by nwolek** [comment]
Following up today. I went through the demo and help patchers and the presets work fine. However, in the [train.shift~] and [phasor.shift~] help patches, it looks like I never added any presets. Not really sure they are necessary for these objects, so I will be eliminating them to avoid confusion.

**Pull request merged**
