### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tap**

### CODE REVIEW

**Comment by nwolek** [comment]
So does the removal of the old dsp and perform methods effectively end 32 bit support ?

**Comment by tap** [comment]
To be clear: 32-bit Max binary support is separate from 32-bit audio support.

Your externs would not load in a 32-bit audio version of Max (meaning prior to Max 6) anyway because they call the `dsp_add64()` function.  So this work really is just "cleanup" and there is no functional impact either way.

**Comment by nwolek** [comment]
Ah, I think I was confusing the binary and audio support.

However, I seem to recall leaving the 32-bit methods in there in case some poor soul wanted to compile them for 32-bit platform. All they would need to do is change the line that adds `dsp_add64()` to `dsp_add()`. But I see you point about clean up, and that same hypothetical poor soul could now dig back into the history of this repo.

**Comment by nwolek** [comment]
Not sure now that I should have pushed to this branch, but I guess it works as part of clean up. I was following up on #10 so that more than just the version would stay up to date. The system now uses a common `Info.plist.in` in the source folder for generating all the necessary property lists in the externals.

@tap - Do you think this is something that should be on the developer to implement or do you see a way to handle it within the `max-sdk-core` repo? Either way is fine with me.

**Comment by tap** [comment]
I like what you've done @nwolek -- with a few changes to make the template plist substitute the author name, copyright info, etc. I think this could definitely work as a built-in part of the SDK scripts.  I'll take a swing at integrating that.

**Comment by tap** [comment]
As promised :-) ... The Info.plist stuff is integrated into the SDK submodule.  The values that are used in the Info.plist are defined in the `package-info.json` file in a special key that we've added this week for just this purpose called `package_extra`.

**Comment by nwolek** [comment]
I trashed my externals and build folder, then stepped through the build process again using Cmake, not Xcode. One line in the new Info.plist looks wrong:

```
	<key>CFBundleIdentifier</key>
	<string>com.nathanwolek.${PRODUCT_NAME:rfc1034identifier}</string>
```

Is this what happens on your machine at commit b0797ef @tap?

**Comment by tap** [comment]
That should be correct -- Cmake will generate this and then when Xcode
builds it will perform the next substitution with a legal version of the
actual extern name.

best,
  Tim

**Comment by nwolek** [comment]
Sorry, I should have been clearer (it was late last night when I checked it). I used `make` to build (not Xcode) and it produced that line. Steps were:

```
mkdir build
cd build
cmake ..
make
```

I hope my lack of clarity doesn't change the fix you are working on!

**Comment by tap** [comment]
Upon further digging, here is what I now know:

1. I was building on the command line using `cmake -G Xcode .. && cmake --build .` instead of `cmake .. && make`.  When building with Xcode the substitution works, when not building with Xcode it does not.
2. Having tried updating the Travis config use Xcode, it fails -- it seems that the version of Xcode they use cannot parse the output of the version of CMake they use.  Or something like that.  It's difficult to tell exactly.
3. The thing that this particular substitution is trying to accomplish is that CFBundle identifiers must adhere to RFC 1034 in its naming specification.  Thus, underscores, tildes, etc. are illegal.  We can accomplish this without Xcode and so that's what I'll take on next.
4. Sigh. It's hard to get this stuff all correct despite the apparent simplicity from the outside view.

**Comment by tap** [comment]
Contrary to the above, the failures I was experience were actually due to the flag in the travis file forcing it to use an ancient version of Xcode.  Hooray!

**Comment by nwolek** [comment]
I can confirm that new directions in [HowToBuild.md](https://github.com/nwolek/LowkeyNW/blob/cleanup/source/HowToBuild.md) work here on my machine. I'll move forward with a merge then tag a release.

**Pull request merged**
